export const dataVehiclesProducts = [
  {
    id: 'id1',
    brand: 'Toyota',
    image_url: '/toyota/all-new-alphard-hev.png',
    name: 'All New Alphard',
    price_with_driver: 1000000,
    price_with_no_driver: 550000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id2',
    brand: 'Toyota',
    image_url: '/toyota/all-new-avanza.png',
    name: 'All New Avanza',
    price_with_driver: 600000,
    price_with_no_driver: 450000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id3',
    brand: 'Toyota',
    image_url: '/toyota/all-new-kijang-innova-zenix-hev.png',
    name: 'All New Kijang Innova Zenix HEV',
    price_with_driver: 2500000,
    price_with_no_driver: 1550000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id4',
    brand: 'Toyota',
    image_url: '/toyota/all-new-veloz.png',
    name: 'All New Veloz',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id5',
    brand: 'Toyota',
    image_url: '/toyota/all-new-voxy.png',
    name: 'All New Voxy',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id6',
    brand: 'Honda',
    image_url: '/honda/all-new-honda-crv-rs-hev.png',
    name: 'All New Honda CR-V RS HEV',
    price_with_driver: 850000,
    price_with_no_driver: 550000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id7',
    brand: 'Honda',
    image_url: '/honda/all-new-honda-hrv-e-cvt.png',
    name: 'All New Honda HR-V E CVT',
    price_with_driver: 850000,
    price_with_no_driver: 550000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id8',
    brand: 'Honda',
    image_url: '/honda/honda-br-v-prestige-cvt.png',
    name: 'Honda BR-V Prestige CVT',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id9',
    brand: 'Honda',
    image_url: '/honda/honda-brio-rs-cvt.png',
    name: 'Honda Brio RS CVT',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id10',
    brand: 'Honda',
    image_url: '/honda/honda-wrv-e-cvt.png',
    name: 'Honda WRV E CVT',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id11',
    brand: 'Honda',
    image_url: '/honda/new-honda-br-v-n7x-e-cvt.png',
    name: 'New Honda BR-V N7X E CVT',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id12',
    brand: 'Mitsubishi',
    image_url: '/mitsubishi/new-pajero-sport-limited-edition.png',
    name: 'New Pajero Sport Limited Edition',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id13',
    brand: 'Mitsubishi',
    image_url: '/mitsubishi/new-pajero-sport.png',
    name: 'New Pajero Sport',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id14',
    brand: 'Mitsubishi',
    image_url: '/mitsubishi/x-force.png',
    name: 'X Force',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id15',
    brand: 'Mitsubishi',
    image_url: '/mitsubishi/xpander.png',
    name: 'Xpander Cross',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id16',
    brand: 'Mitsubishi',
    image_url: '/mitsubishi/xpander.png',
    name: 'Xpander',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id17',
    brand: 'Hyundai',
    image_url: '/hyundai/creta-alpha-edition.png',
    name: 'Creta Alpha Edition',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id18',
    brand: 'Hyundai',
    image_url: '/hyundai/new-creta-ivt-prime.png',
    name: 'New Creta IVT Prime',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id19',
    brand: 'Hyundai',
    image_url: '/hyundai/new-creta-n-line-turbo.png',
    name: 'New Creta N Line Turbo',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id20',
    brand: 'Hyundai',
    image_url: '/hyundai/stargazer-x.png',
    name: 'Stargazer X',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id21',
    brand: 'Hyundai',
    image_url: '/hyundai/stargazer.png',
    name: 'Stargazer',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id22',
    brand: 'Hyundai',
    image_url: '/hyundai/staria.png',
    name: 'Staria',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id23',
    brand: 'Hyundai',
    image_url: '/hyundai/the-new-tucson-hev.png',
    name: 'The New Tucson HEV',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
]
