export const mostDataCarRents = [
  {
    id: 'id1',
    brand: 'Toyota',
    image_url: '/toyota/all-new-alphard-hev.png',
    name: 'All New Alphard',
    price_with_driver: 1000000,
    price_with_no_driver: 550000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id2',
    brand: 'Toyota',
    image_url: '/toyota/all-new-avanza.png',
    name: 'All New Avanza',
    price_with_driver: 600000,
    price_with_no_driver: 450000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id3',
    brand: 'Toyota',
    image_url: '/toyota/all-new-kijang-innova-zenix-hev.png',
    name: 'All New Kijang Innova Zenix HEV',
    price_with_driver: 2500000,
    price_with_no_driver: 1550000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
  {
    id: 'id4',
    brand: 'Toyota',
    image_url: '/toyota/all-new-veloz.png',
    name: 'All New Veloz',
    price_with_driver: 500000,
    price_with_no_driver: 350000,
    duration: '12h',
    transmission: 'AT/MT',
    passengers: 5,
    fuelType: 'Bio Solar',
  },
]
